FROM postgres:14.9

# # this is a standard command that says copy tables(user, post and comment) from the postgres tables folder to the containers tables folder
# Add /tables/ /docker-entrypoint-initdb.d/tables/

# # copy files from the seed folder to the containers seed folder
# Add /seed/ /docker-entrypoint-initdb.d/seed/

# # excute the commands to create tables
# Add deploy_schemas.sql /docker-entrypoint-initdb.d/